name: hims
recipe: lamp
volumes:
  - $LANDO_APP_ROOT/database:/var/lib/mysql
config:
  webroot: .
  php: '7.4'
  composer_version: '2.0.3'
  database: mysql:5.7
  xdebug: true
  config:
    database: lamp
    username: lamp
    password: lamp
    host: database
services:
  myservice:
    type: phpmyadmin
  appserver:
    build_as_root:
      - apt-get update -y
      - apt-get install cron -y
      - php index.php migrate
    run_as_root:
      - crontab -l | { cat; echo "* * * * * /usr/local/bin/php -d memory_limit=-1 /app/index.php Cron followup >> /var/log/cronfollowup_$LANDO_APP_NAME.log 2>&1"; } | crontab -
      - crontab -l | { cat; echo "* * * * * /usr/local/bin/php -d memory_limit=-1 /app/index.php Cron test >> /var/log/crontest_$LANDO_APP_NAME.log 2>&1"; } | crontab -
      - service cron start
    run:
      #- crontab /app/application/config/cron.txt
      #- service cron status
      #- crontab –l