<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;
use Spatie\Activitylog\Models\Concerns\LogsActivity;
use Spatie\Activitylog\Support\LogOptions;

class Transaction extends Model
{
    use HasFactory, LogsActivity;

    public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults()
            ->logAll()
            ->logOnlyDirty()
            ->dontLogEmptyChanges();
    }

    protected $fillable = [
        'id',
        'tr_number',
        'old_id',
        'closing_id',
        'created_by',
        'patient_id',
        'panel_id',
        'receaveable_id',
        'type',
        'income_or_expense',
        'amount',
        'amount_alphabetical',
        'orignal_amount',
        'customer_payed',
        'change',
        'edited_amount',
        'is_refunded',
        'expense_category_id',
        'exp_voucher_id',
        'notes',
        'created_at',
        'updated_at',
    ];

    protected $appends = [
        'year',
        'month',
        'day',
        'number',
    ];

    protected function casts(): array
    {
        return [
            'is_refunded' => 'boolean',
        ];
    }

    public function getYearAttribute()
    {
        return $this->tr_number_parts['year'] ?? null;
    }

    public function getMonthAttribute()
    {
        return $this->tr_number_parts['month'] ?? null;
    }

    public function getDayAttribute()
    {
        return $this->tr_number_parts['day'] ?? null;
    }

    public function getNumberAttribute()
    {
        return $this->tr_number_parts['number'] ?? null;
    }

    public function getTrNumberPartsAttribute()
    {
        if (empty($this->tr_number)) {
            return null;
        }

        $parts = explode('/', $this->tr_number);

        return [
            'year' => $parts[1] ?? null,
            'month' => $parts[2] ?? null,
            'day' => $parts[3] ?? null,
            'number' => $parts[4] ?? null,
        ];
    }

    public function updateCounter(): void
    {
        $closing = $this->closing;
        if ($closing) {
            $totalIncAmount = $closing->transactions()->where('income_or_expense', 'INCOME')->sum('amount');
            $totalExpAmount = $closing->transactions()->where('income_or_expense', 'EXPENSE')->sum('amount');
            $closing->closing_amount = $totalIncAmount - $totalExpAmount;
            $closing->expense_payed = $totalExpAmount;
            $closing->saveQuietly();
        }
    }

    public function elements()
    {
        return $this->hasMany(TransactionElement::class);
    }

    public function patient()
    {
        return $this->belongsTo(Patient::class);
    }

    public function receaveable()
    {
        return $this->hasOne(Receaveable::class, 'transaction_id');
    }

    public function closing()
    {
        return $this->belongsTo(Closing::class, 'closing_id');
    }

    public function panel()
    {
        return $this->belongsTo(Panel::class, 'panel_id');
    }

    public function refundBy(User $user): void
    {
        if ($this->is_refunded) {
            throw ValidationException::withMessages([
                'transaction' => 'Transaction is already refunded.',
            ]);
        }

        DB::transaction(function () use ($user): void {
            $this->update([
                'is_refunded' => true,
            ]);

            if ($this->receaveable) {
                $this->receaveable->update([
                    'status' => 'cancelled',
                    'amount' => 0,
                ]);
            }

            TransactionElement::create([
                'closing_id' => $this->closing_id,
                'transaction_id' => $this->id,
                'created_by' => $user->id,
                'patient_id' => $this->patient_id,
                'type' => 'REFUND',
                'income_or_expense' => 'EXPENSE',
                'amount' => $this->amount,
                'orignal_amount' => $this->orignal_amount ?? $this->amount,
                'refunded_transaction_id' => $this->id,
                'notes' => 'Refund generated by admin action.',
            ]);
        });
    }

    public static function generateTransactionNumber(): string
    {
        return DB::transaction(function () {
            $now = Carbon::now();
            $year = $now->format('Y');
            $month = $now->format('m');
            $day = $now->format('d');

            // Count how many patients have been created this month with PS numbers
            // Use FOR UPDATE to lock the table and prevent race conditions
            $count = self::where('tr_number', 'like', "TR/{$year}/{$month}/{$day}%")
                ->lockForUpdate()
                ->count();
            $count += 1; // Increment for the new patient

            // Pad the count to be 4 digits
            $count = str_pad($count, 4, '0', STR_PAD_LEFT);

            return "TR/{$year}/{$month}/{$day}/{$count}";
        });
    }
}
